/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import avaliacao.Adicionais;
import avaliacao.Assados;
import avaliacao.Bebidas;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.DaoImplAdicional;
import model.bean.DaoImplAssados;
import model.bean.DaoImplBebidas;

/**
 *
 * @author felipedania
 */
public class TestaGestor extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    public TestaGestor() {
        initComponents();
        DefaultTableModel tabelaProdutos = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(tabelaProdutos));
        readJTable1();
    }

    public void readJTable1() {
        DefaultTableModel tabelaProdutos = (DefaultTableModel) jTable1.getModel();
        tabelaProdutos.setNumRows(0);
        model.bean.DaoImplBebidas bDao = new DaoImplBebidas();
        model.bean.DaoImplAssados aDao = new DaoImplAssados();
        model.bean.DaoImplAdicional adDao = new DaoImplAdicional();

        for (Adicionais adicional : adDao.readAdicionais()) {
            tabelaProdutos.addRow(new Object[]{
                adicional.getQuantidadeAdicionais(),
                adicional.getNomeAdicionais(),
                adicional.getValorAdicionais()
            });
        }

        for (Bebidas bebida : bDao.readBebidas()) {
            tabelaProdutos.addRow(new Object[]{
                bebida.getQuantidade(),
                bebida.getNome(),
                bebida.getValor()
            });
        }

        for (Assados assado : aDao.readAssados()) {
            tabelaProdutos.addRow(new Object[]{
                assado.getQuantidade(),
                assado.getNome(),
                assado.getValor()
            });
        }
    }

    public void readJTable1ForLike(String descricao) {
        DefaultTableModel tabelaProdutos = (DefaultTableModel) jTable1.getModel();
        tabelaProdutos.setNumRows(0);
        model.bean.DaoImplBebidas bDao = new DaoImplBebidas();
        model.bean.DaoImplAssados aDao = new DaoImplAssados();
        model.bean.DaoImplAdicional adDao = new DaoImplAdicional();

        for (Bebidas bebida : bDao.buscaForLikeBebida(descricao)) {
            tabelaProdutos.addRow(new Object[]{
                bebida.getQuantidade(),
                bebida.getNome(),
                bebida.getValor()
            });
        }

        for (Adicionais adicional : adDao.buscaForLikeAdicional(descricao)) {
            tabelaProdutos.addRow(new Object[]{
                adicional.getQuantidadeAdicionais(),
                adicional.getNomeAdicionais(),
                adicional.getValorAdicionais()
            });
        }

        for (Assados assado : aDao.buscaForLikeAssados(descricao)) {
            tabelaProdutos.addRow(new Object[]{
                assado.getQuantidade(),
                assado.getNome(),
                assado.getValor()
            });
        }
    }

    private boolean validaSalvarContato() {
        String msg = "";
        Boolean verificar = true;
        if (jTextField1.getText().equals("")) {
            msg += "* nome é obrigatório \n";
            verificar = false;
        }
        if (cbTipo.getSelectedItem().toString().equals("Selecione um tipo")) {
            msg += "* tipo é obrigatório \n";
            verificar = false;
        }
        if (jTextField12.getText().equals("")) {
            msg += "* valor é obrigatório \n";
            verificar = false;
        }
        if (!verificar) {
            JOptionPane.showMessageDialog(null, msg);
        }
        return verificar;
    }

    private void limparCampos() {
        cbTipo.setSelectedItem("Selecione um tipo");
        jTextField1.setText(null);
        jTextField12.setText(null);
        jTextField2.setText(null);
        jTextField22.setText(null);
        jTextField3.setText(null);
        jTextField32.setText(null);
        jTextField4.setText(null);
        jTextField42.setText(null);
        jTextField5.setText(null);
        jTextField52.setText(null);
        QTD1.setText(null);
        QTD2.setText(null);
        QTD3.setText(null);
        QTD4.setText(null);
        QTD5.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField52 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSALVAR = new javax.swing.JButton();
        jButtonALTERAR = new javax.swing.JButton();
        jButtonFECHAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbTipo = new javax.swing.JComboBox<>();
        jButtonREMOVER = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        QTD1 = new javax.swing.JTextField();
        QTD2 = new javax.swing.JTextField();
        QTD3 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        QTD4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        QTD5 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextFieldBUSCA = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButtonBUSCAR = new javax.swing.JButton();
        jTextField42 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DESCRIÇÃO");

        jLabel2.setText("VALOR");

        jButtonSALVAR.setText("SALVAR");
        jButtonSALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALVARActionPerformed(evt);
            }
        });

        jButtonALTERAR.setText("ALTERAR");
        jButtonALTERAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonALTERARMouseClicked(evt);
            }
        });
        jButtonALTERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonALTERARActionPerformed(evt);
            }
        });

        jButtonFECHAR.setText("ENCERRAR");
        jButtonFECHAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFECHARActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade", "Nome", "Valor", "ID", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma categoria", "Assado", "Bebida", "Adicional" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jButtonREMOVER.setText("REMOVER");
        jButtonREMOVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREMOVERActionPerformed(evt);
            }
        });

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("QUANTIDADE");

        jButtonBUSCAR.setText("BUSCAR");
        jButtonBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBUSCARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFECHAR)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(QTD1)
                                    .addComponent(QTD2)
                                    .addComponent(QTD3)
                                    .addComponent(QTD4)
                                    .addComponent(QTD5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel2)
                                                .addGap(177, 177, 177)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSALVAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonALTERAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonREMOVER)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBUSCA, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonBUSCAR)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(4, 4, 4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonFECHAR)))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QTD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QTD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QTD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(QTD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addComponent(QTD5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonALTERAR)
                    .addComponent(jButtonSALVAR)
                    .addComponent(jButtonREMOVER)
                    .addComponent(jTextFieldBUSCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBUSCAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALVARActionPerformed
        if (validaSalvarContato()) {
            model.bean.DaoImplBebidas bDao = new DaoImplBebidas();
            model.bean.DaoImplAssados aDao = new DaoImplAssados();
            model.bean.DaoImplAdicional adDao = new DaoImplAdicional();
            //            Produtos cardapio = new Produtos();
            //            Produtos bebidas = new Produtos();
            //Cardapio cardapioTipos = new Cardapio();

            //System.out.println(cbTipo.getSelectedIndex());
            switch (cbTipo.getSelectedItem().toString()) {//0-Selecione um tipo 1-Assado 2-Bebida 3-Adicional
                case "Assado":
                    Assados a = new Assados();
                    a.setQuantidade(Integer.parseInt(QTD1.getText()));
                    a.setNome(jTextField1.getText());
                    a.setValor(Double.parseDouble(jTextField12.getText()));
                    aDao.insertAssados(a);
                    break;
                case "Bebida":
                    Bebidas b = new Bebidas();
                    b.setQuantidade(Integer.parseInt(QTD1.getText()));
                    b.setNome(jTextField1.getText());
                    b.setValor(Double.parseDouble(jTextField12.getText()));
                    bDao.insertBebidas(b);
                    break;
                case "Adicional":
                    Adicionais ad = new Adicionais();
                    ad.setQuantidadeAdicionais(Integer.parseInt(QTD1.getText()));
                    ad.setNomeAdicionais(jTextField1.getText());
                    ad.setValorAdicionais(Double.parseDouble(jTextField12.getText()));
                    adDao.insertAdicionais(ad);
                    break;

            }
        }

        //LIMPAR CAMPOS
        cbTipo.setSelectedItem("Selecione um tipo");
        jTextField1.setText(null);
        jTextField12.setText(null);
        jTextField2.setText(null);
        jTextField22.setText(null);
        jTextField3.setText(null);
        jTextField32.setText(null);
        jTextField4.setText(null);
        jTextField42.setText(null);
        jTextField5.setText(null);
        jTextField52.setText(null);
        QTD1.setText(null);
        QTD2.setText(null);
        QTD3.setText(null);
        QTD4.setText(null);
        QTD5.setText(null);

        //MOSTRANDO VALORES NA JTABLE
        readJTable1();
    }//GEN-LAST:event_jButtonSALVARActionPerformed

    private void jButtonALTERARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonALTERARMouseClicked
        if (jTable1.getSelectedRow() != -1) {
            QTD1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jTextField12.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_jButtonALTERARMouseClicked

    private void jButtonALTERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonALTERARActionPerformed
        String menu;
        menu = JOptionPane.showInputDialog("Digite a opção desejada \n1- Assado \n2- Bebida \n3- Adicional \nS- Sair");

        if (jTable1.getSelectedRow() != -1) {
            switch (menu) {//0-Selecione um tipo 1-Assado 2-Bebida 3-Adicional
                case "Assado":
                    Assados a = new Assados();
                    model.bean.DaoImplAssados aDao = new DaoImplAssados();
                    a.setQuantidade(Integer.parseInt(QTD1.getText()));
                    a.setNome(jTextField1.getText());
                    a.setValor(Double.parseDouble(jTextField12.getText()));
                    a.setIdAssados((int) jTable1.getValueAt(jTable1.getSelectedRow(), 3));
                    aDao.updateAssados(a);
                    break;
                case "Bebida":
                    model.bean.DaoImplBebidas bDao = new DaoImplBebidas();
                    Bebidas b = new Bebidas();
                    b.setQuantidade(Integer.parseInt(QTD1.getText()));
                    b.setNome(jTextField1.getText());
                    b.setValor(Double.parseDouble(jTextField12.getText()));
                    b.setIdBebidas((int) jTable1.getValueAt(jTable1.getSelectedRow(), 3));
                    bDao.updateBebidas(b);
                    break;
                case "Adicional":
                    Adicionais ad = new Adicionais();
                    model.bean.DaoImplAdicional adDao = new DaoImplAdicional();
                    ad.setQuantidadeAdicionais(Integer.parseInt(QTD1.getText()));
                    ad.setNomeAdicionais(jTextField1.getText());
                    ad.setValorAdicionais(Double.parseDouble(jTextField12.getText()));
                    ad.setIdAdicionais((int) jTable1.getValueAt(jTable1.getSelectedRow(), 4));
                    adDao.updateAdicionais(ad);
                    break;

            }
        }

        //LIMPAR CAMPOS
        cbTipo.setSelectedItem("Selecione um tipo");
        jTextField1.setText(null);
        jTextField12.setText(null);
        jTextField2.setText(null);
        jTextField22.setText(null);
        jTextField3.setText(null);
        jTextField32.setText(null);
        jTextField4.setText(null);
        jTextField42.setText(null);
        jTextField5.setText(null);
        jTextField52.setText(null);
        QTD1.setText(null);
        QTD2.setText(null);
        QTD3.setText(null);
        QTD4.setText(null);
        QTD5.setText(null);

        //MOSTRANDO VALORES NA JTABLE
        readJTable1();
    }//GEN-LAST:event_jButtonALTERARActionPerformed

    private void jButtonFECHARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFECHARActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFECHARActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {
            QTD1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jTextField12.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {
            QTD1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jTextField12.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void jButtonREMOVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREMOVERActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            String menu;
            menu = JOptionPane.showInputDialog("Digite a opção desejada \n1- Assado \n2- Bebida \n3- Adicional \nS- Sair");

            switch (menu) {//0-Selecione um tipo 1-Assado 2-Bebida 3-Adicional
                case "1":
                    model.bean.DaoImplAssados aDao = new DaoImplAssados();
                    Assados a = new Assados();
                    a.setIdAssados((int) jTable1.getValueAt(jTable1.getSelectedRow(), 4));
                    aDao.deleteAssados(a);
                    break;
                case "2":
                    model.bean.DaoImplBebidas bDao = new DaoImplBebidas();
                    Bebidas b = new Bebidas();
                    b.setIdBebidas((int) jTable1.getValueAt(jTable1.getSelectedRow(), 4));
                    bDao.deleteBebidas(b);
                    break;
                case "3":
                    model.bean.DaoImplAdicional adDao = new DaoImplAdicional();
                    Adicionais ad = new Adicionais();
                    ad.setIdAdicionais((int) jTable1.getValueAt(jTable1.getSelectedRow(), 4));
                    adDao.deleteAdicionais(ad);
                    break;
            }

            //LIMPAR CAMPOS
            cbTipo.setSelectedItem("Selecione um tipo");
            jTextField1.setText(null);
            jTextField12.setText(null);
            jTextField2.setText(null);
            jTextField22.setText(null);
            jTextField3.setText(null);
            jTextField32.setText(null);
            jTextField4.setText(null);
            jTextField42.setText(null);
            jTextField5.setText(null);
            jTextField52.setText(null);
            QTD1.setText(null);
            QTD2.setText(null);
            QTD3.setText(null);
            QTD4.setText(null);
            QTD5.setText(null);

            //MOSTRANDO VALORES NA JTABLE
            readJTable1();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir");
        }
    }//GEN-LAST:event_jButtonREMOVERActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TestaCardapio telaCardapio = new TestaCardapio();
        telaCardapio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBUSCARActionPerformed
        if (!jTextFieldBUSCA.getText().equalsIgnoreCase("")) {
            readJTable1ForLike(jTextFieldBUSCA.getText());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha com a busca ao lado");
            jTextFieldBUSCA.setBackground(Color.red);
        }
    }//GEN-LAST:event_jButtonBUSCARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestaGestor().setVisible(true);
            }
        });
    }

    public JTextField getQTD1() {
        return QTD1;
    }

    public void setQTD1(JTextField QTD1) {
        this.QTD1 = QTD1;
    }

    public JTextField getQTD2() {
        return QTD2;
    }

    public void setQTD2(JTextField QTD2) {
        this.QTD2 = QTD2;
    }

    public JTextField getQTD3() {
        return QTD3;
    }

    public void setQTD3(JTextField QTD3) {
        this.QTD3 = QTD3;
    }

    public JTextField getQTD4() {
        return QTD4;
    }

    public void setQTD4(JTextField QTD4) {
        this.QTD4 = QTD4;
    }

    public JTextField getQTD5() {
        return QTD5;
    }

    public void setQTD5(JTextField QTD5) {
        this.QTD5 = QTD5;
    }

    public JComboBox<String> getCbTipo() {
        return cbTipo;
    }

    public void setCbTipo(JComboBox<String> cbTipo) {
        this.cbTipo = cbTipo;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButtonALTERAR() {
        return jButtonALTERAR;
    }

    public void setjButtonALTERAR(JButton jButtonALTERAR) {
        this.jButtonALTERAR = jButtonALTERAR;
    }

    public JButton getjButtonBUSCAR() {
        return jButtonBUSCAR;
    }

    public void setjButtonBUSCAR(JButton jButtonBUSCAR) {
        this.jButtonBUSCAR = jButtonBUSCAR;
    }

    public JButton getjButtonFECHAR() {
        return jButtonFECHAR;
    }

    public void setjButtonFECHAR(JButton jButtonFECHAR) {
        this.jButtonFECHAR = jButtonFECHAR;
    }

    public JButton getjButtonREMOVER() {
        return jButtonREMOVER;
    }

    public void setjButtonREMOVER(JButton jButtonREMOVER) {
        this.jButtonREMOVER = jButtonREMOVER;
    }

    public JButton getjButtonSALVAR() {
        return jButtonSALVAR;
    }

    public void setjButtonSALVAR(JButton jButtonSALVAR) {
        this.jButtonSALVAR = jButtonSALVAR;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JTextField getjTextField12() {
        return jTextField12;
    }

    public void setjTextField12(JTextField jTextField12) {
        this.jTextField12 = jTextField12;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    public JTextField getjTextField22() {
        return jTextField22;
    }

    public void setjTextField22(JTextField jTextField22) {
        this.jTextField22 = jTextField22;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public void setjTextField3(JTextField jTextField3) {
        this.jTextField3 = jTextField3;
    }

    public JTextField getjTextField32() {
        return jTextField32;
    }

    public void setjTextField32(JTextField jTextField32) {
        this.jTextField32 = jTextField32;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public void setjTextField4(JTextField jTextField4) {
        this.jTextField4 = jTextField4;
    }

    public JTextField getjTextField42() {
        return jTextField42;
    }

    public void setjTextField42(JTextField jTextField42) {
        this.jTextField42 = jTextField42;
    }

    public JTextField getjTextField5() {
        return jTextField5;
    }

    public void setjTextField5(JTextField jTextField5) {
        this.jTextField5 = jTextField5;
    }

    public JTextField getjTextField52() {
        return jTextField52;
    }

    public void setjTextField52(JTextField jTextField52) {
        this.jTextField52 = jTextField52;
    }

    public JTextField getjTextFieldBUSCA() {
        return jTextFieldBUSCA;
    }

    public void setjTextFieldBUSCA(JTextField jTextFieldBUSCA) {
        this.jTextFieldBUSCA = jTextFieldBUSCA;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QTD1;
    private javax.swing.JTextField QTD2;
    private javax.swing.JTextField QTD3;
    private javax.swing.JTextField QTD4;
    private javax.swing.JTextField QTD5;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonALTERAR;
    private javax.swing.JButton jButtonBUSCAR;
    private javax.swing.JButton jButtonFECHAR;
    private javax.swing.JButton jButtonREMOVER;
    private javax.swing.JButton jButtonSALVAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextFieldBUSCA;
    // End of variables declaration//GEN-END:variables
}
