/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import avaliacao.Adicionais;
import avaliacao.Assados;
import avaliacao.Bebidas;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.DaoImplAdicional;
import model.bean.DaoImplAssados;
import model.bean.DaoImplBebidas;

/**
 *
 * @author felipedania
 */
public class TestaCardapio extends javax.swing.JFrame {

    /**
     * Creates new form TestaCardapio
     */
    public TestaCardapio() {
        initComponents();
        DefaultTableModel tabelaProdutosAssados = (DefaultTableModel) jTableAssados.getModel();
        DefaultTableModel tabelaProdutosAdicionais = (DefaultTableModel) jTableAdicionais.getModel();
        DefaultTableModel tabelaProdutosBebidas = (DefaultTableModel) jTableBebidas.getModel();
        jTableAssados.setRowSorter(new TableRowSorter(tabelaProdutosAssados));
        jTableAdicionais.setRowSorter(new TableRowSorter(tabelaProdutosAdicionais));
        jTableBebidas.setRowSorter(new TableRowSorter(tabelaProdutosBebidas));
        readJTableAdicionais();
        readJTableAssados();
        readJTableBebidas();
    }

    public void readJTableAdicionais() {
        DefaultTableModel tabelaProdutosAdicionais = (DefaultTableModel) jTableAdicionais.getModel();
        tabelaProdutosAdicionais.setNumRows(0);
        model.bean.DaoImplAdicional adDao = new DaoImplAdicional();
        for (Adicionais adicional : adDao.readAdicionais()) {
            tabelaProdutosAdicionais.addRow(new Object[]{
                adicional.getQuantidadeAdicionais(),
                adicional.getNomeAdicionais(),
                adicional.getValorAdicionais()
            });
        }
    }

    public void readJTableAssados() {
        DefaultTableModel tabelaProdutosAssados = (DefaultTableModel) jTableAssados.getModel();
        tabelaProdutosAssados.setNumRows(0);
        model.bean.DaoImplAssados aDao = new DaoImplAssados();
        for (Assados assado : aDao.readAssados()) {
            tabelaProdutosAssados.addRow(new Object[]{
                assado.getQuantidade(),
                assado.getNome(),
                assado.getValor()
            });
        }
    }

    public void readJTableBebidas() {
        DefaultTableModel tabelaProdutosBebidas = (DefaultTableModel) jTableBebidas.getModel();
        tabelaProdutosBebidas.setNumRows(0);
        model.bean.DaoImplBebidas bDao = new DaoImplBebidas();
        for (Bebidas bebida : bDao.readBebidas()) {
            tabelaProdutosBebidas.addRow(new Object[]{
                bebida.getQuantidade(),
                bebida.getNome(),
                bebida.getValor()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAssados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAdicionais = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableBebidas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldQTD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        valor2 = new javax.swing.JLabel();
        valor1 = new javax.swing.JLabel();
        valor3 = new javax.swing.JLabel();
        descricao1 = new javax.swing.JLabel();
        valor4 = new javax.swing.JLabel();
        descricao2 = new javax.swing.JLabel();
        descricao3 = new javax.swing.JLabel();
        descricao4 = new javax.swing.JLabel();
        QTD1 = new javax.swing.JLabel();
        QTD2 = new javax.swing.JLabel();
        QTD3 = new javax.swing.JLabel();
        QTD4 = new javax.swing.JLabel();
        jButtonEncerrar = new javax.swing.JButton();

        jLabel10.setText("QUALQUER COISA");

        jLabel19.setText("QTD");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CARDAPIO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Adicionais");

        jTableAssados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade", "Nome", "Valor", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAssados.getTableHeader().setReorderingAllowed(false);
        jTableAssados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAssadosMouseClicked(evt);
            }
        });
        jTableAssados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableAssadosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAssados);

        jLabel3.setText("Assados");

        jTableAdicionais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade", "Nome", "Valor", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAdicionais.getTableHeader().setReorderingAllowed(false);
        jTableAdicionais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAdicionaisMouseClicked(evt);
            }
        });
        jTableAdicionais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableAdicionaisKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTableAdicionais);

        jTableBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade", "Nome", "Valor", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBebidas.getTableHeader().setReorderingAllowed(false);
        jTableBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBebidasMouseClicked(evt);
            }
        });
        jTableBebidas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableBebidasKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTableBebidas);

        jLabel4.setText("Bebidas");

        jTextFieldQTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQTDActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade");

        jButton2.setText("ALTERAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("PAINEL COM TODOS ITENS SELECIONADOS, FORMANDO O PEDIDO");

        QTD1.setText("1");

        QTD2.setText("2");

        QTD3.setText("3");

        QTD4.setText("4");

        jButtonEncerrar.setText("Encerrar");
        jButtonEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEncerrar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTextFieldQTD, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(jButton2))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6)
                                .addContainerGap(92, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QTD1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QTD2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QTD3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QTD4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descricao3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descricao4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valor3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valor4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(55, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QTD1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QTD2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricao3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QTD3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descricao4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QTD4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonEncerrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldQTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldQTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQTDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQTDActionPerformed

    private void jTableAdicionaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAdicionaisMouseClicked
        /*if(jTableAdicionais.getSelectedRow() != -1){
            DefaultTableModel tAdicionais = (DefaultTableModel) jTableAdicionais.getModel();
            tAdicionais.removeRow(jTableAdicionais.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir");
        }*/

        if (jTableAdicionais.getSelectedRow() != -1) {
            jTextFieldQTD.setText(jTableAdicionais.getValueAt(jTableAdicionais.getSelectedRow(), 0).toString());
        }

    }//GEN-LAST:event_jTableAdicionaisMouseClicked

    private void jTableAdicionaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAdicionaisKeyReleased
        // TODO add your handling code here:
        if (jTableAdicionais.getSelectedRow() != -1) {
            jTextFieldQTD.setText(jTableAdicionais.getValueAt(jTableAdicionais.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jTableAdicionaisKeyReleased

    private void jTableAssadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAssadosKeyReleased
        // TODO add your handling code here:

        if (jTableAssados.getSelectedRow() != -1) {
            jTextFieldQTD.setText(jTableAssados.getValueAt(jTableAssados.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jTableAssadosKeyReleased

    private void jTableAssadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAssadosMouseClicked
        // TODO add your handling code here:
        if (jTableAssados.getSelectedRow() != -1) {
            jTextFieldQTD.setText(jTableAssados.getValueAt(jTableAssados.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jTableAssadosMouseClicked

    private void jTableBebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBebidasMouseClicked
        // TODO add your handling code here:
        if (jTableBebidas.getSelectedRow() != -1) {
            jTextFieldQTD.setText(jTableBebidas.getValueAt(jTableBebidas.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jTableBebidasMouseClicked

    private void jTableBebidasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableBebidasKeyReleased
        // TODO add your handling code here:
        if (jTableBebidas.getSelectedRow() != -1) {
            jTextFieldQTD.setText(jTableBebidas.getValueAt(jTableBebidas.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jTableBebidasKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

//        valor2.setText(jTextFieldQTD.getText());
        if (jTableBebidas.getSelectedRow() != -1) {
            jTableBebidas.setValueAt(QTD1.getText(), jTableBebidas.getSelectedRow(), 0);//QTD
            jTableBebidas.setValueAt(descricao1.getText(), jTableBebidas.getSelectedRow(), 1);//nome
            jTableBebidas.setValueAt(valor1.getText(), jTableBebidas.getSelectedRow(), 2);//valor        
            readJTableBebidas();
        }
        if (jTableAdicionais.getSelectedRow() != -1) {
            jTableAdicionais.setValueAt(QTD1.getText(), jTableAdicionais.getSelectedRow(), 0);//QTD
            jTableAdicionais.setValueAt(descricao1.getText(), jTableAdicionais.getSelectedRow(), 1);//nome
            jTableAdicionais.setValueAt(valor1.getText(), jTableAdicionais.getSelectedRow(), 2);//valor
            readJTableAdicionais();
            
            if (QTD1.getText() != "" && descricao1.getText() != "" && valor1.getText() != "") {
                jTableAdicionais.setValueAt(QTD2.getText(), jTableAdicionais.getSelectedRow(), 0);//QTD
                jTableAdicionais.setValueAt(descricao2.getText(), jTableAdicionais.getSelectedRow(), 1);//nome
                jTableAdicionais.setValueAt(valor2.getText(), jTableAdicionais.getSelectedRow(), 2);//valor
                readJTableAdicionais();
                
                if (QTD2.getText() != "" && descricao2.getText() != "" && valor2.getText() != "") {
                    jTableAdicionais.setValueAt(QTD3.getText(), jTableAdicionais.getSelectedRow(), 0);//QTD
                    jTableAdicionais.setValueAt(descricao3.getText(), jTableAdicionais.getSelectedRow(), 1);//nome
                    jTableAdicionais.setValueAt(valor3.getText(), jTableAdicionais.getSelectedRow(), 2);//valor
                    readJTableAdicionais();
                    
                    if (QTD3.getText() != "" && descricao3.getText() != "" && valor3.getText() != "") {
                        jTableAdicionais.setValueAt(QTD4.getText(), jTableAdicionais.getSelectedRow(), 0);//QTD
                        jTableAdicionais.setValueAt(descricao4.getText(), jTableAdicionais.getSelectedRow(), 1);//nome
                        jTableAdicionais.setValueAt(valor4.getText(), jTableAdicionais.getSelectedRow(), 2);//valor
                        readJTableAdicionais();

                    }
                }
            }
        }

        if (jTableAssados.getSelectedRow() != -1) {
            jTableAssados.setValueAt(QTD1.getText(), jTableAssados.getSelectedRow(), 0);//QTD
            jTableAssados.setValueAt(descricao1.getText(), jTableAssados.getSelectedRow(), 1);//nome
            jTableAssados.setValueAt(valor1.getText(), jTableAssados.getSelectedRow(), 2);//valor
            readJTableAssados();

            if (QTD1.getText() != "" && descricao1.getText() != "" && valor1.getText() != "") {
                jTableAssados.setValueAt(QTD2.getText(), jTableAssados.getSelectedRow(), 0);//QTD
                jTableAssados.setValueAt(descricao2.getText(), jTableAssados.getSelectedRow(), 1);//nome
                jTableAssados.setValueAt(valor2.getText(), jTableAssados.getSelectedRow(), 2);//valor
                readJTableAssados();

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonEncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestaCardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QTD1;
    private javax.swing.JLabel QTD2;
    private javax.swing.JLabel QTD3;
    private javax.swing.JLabel QTD4;
    private javax.swing.JLabel descricao1;
    private javax.swing.JLabel descricao2;
    private javax.swing.JLabel descricao3;
    private javax.swing.JLabel descricao4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEncerrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableAdicionais;
    private javax.swing.JTable jTableAssados;
    private javax.swing.JTable jTableBebidas;
    private javax.swing.JTextField jTextFieldQTD;
    private javax.swing.JLabel valor1;
    private javax.swing.JLabel valor2;
    private javax.swing.JLabel valor3;
    private javax.swing.JLabel valor4;
    // End of variables declaration//GEN-END:variables
}
